altamir-master/ECOMMERCE/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('produtos.urls')),
    path('login/', include('clientes.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

altamir-master/clientes/urls.py
from django.urls import path
from . import views
from clientes.views import UserLoginView, UserCreateView, UserUpdateView

app_name = 'clientes'

urlpatterns = [
    path('', UserLoginView.as_view(), name="login"),
    path('<int:pk>/atualizar', UserUpdateView.as_view(), name='atualizar_cliente'),
    path('cadastro/', UserCreateView.as_view(), name="cadastro"),
    path('sair/', views.deslogar, name="deslogar")
]

altamir-master/produtos/urls.py
from django.urls import path
from . import views

app_name = 'produtos'

urlpatterns = [
    path('', views.index, name="principal"),
]

altamir-master/clientes/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser


class MyUserManager(BaseUserManager):
    def create_user(self, email, password=None):
        """
        Creates and saves a User with the given email, date of
        birth and password.
        """
        if not email:
            raise ValueError("Users must have an email address")

        user = self.model(
            email=self.normalize_email(email),
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            email,
            password=password,
        )
        user.is_admin = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser):
    email = models.EmailField(
        verbose_name="email address",
        max_length=255,
        unique=True,
    )
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = MyUserManager()

    USERNAME_FIELD = "email"

    def __str__(self):
        return self.email

    def has_perm(self, perm, obj=None):
        "Does the user have a specific permission?"
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        "Does the user have permissions to view the app `app_label`?"
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        "Is the user a member of staff?"
        # Simplest possible answer: All admins are staff
        return self.is_admin  # Create your models here.

altamir-master/produtos/models.py
from django.db import models
from django.db import models
import decimal


class Categoria(models.Model):
    nome = models.CharField(max_length=50)

    def __str__(self) -> str:
        return self.nome


class Produto(models.Model):
    nome = models.CharField(max_length=250)
    preco = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    imagem = models.ImageField(upload_to="produtos/")
    categoria = models.ForeignKey(Categoria, on_delete=models.PROTECT)
    criado_em = models.DateTimeField(auto_now_add=True)
    desconto = models.DecimalField(max_digits=5, decimal_places=2, default=0)
    descricao = models.TextField(max_length=9999, default=0)

    def __str__(self) -> str:
        return self.nome

    def discoutend_price(self):
        discounted = self.preco - (self.preco * (self.desconto / 100))
        return round(discounted, 2)

altamir-master/clientes/forms.py
from django import forms
from clientes.models import User


class UserCreateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['email', 'password']

    def save(self, commit=True):
        password = self.cleaned_data['password']
        user = super().save(commit=False)
        user.set_password(password)
        if commit:
            user.save()        
        return user

altamir-master/clientes/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from django.contrib.auth import get_user_model, logout
from django.contrib import messages
from django.contrib.auth.views import LoginView
from django.http import Http404, HttpResponse   
from django.urls import reverse_lazy
from django.contrib.auth.forms import AuthenticationForm
from clientes.forms import UserCreateForm
from django.contrib.messages.views import SuccessMessageMixin
from clientes.models import User
from django.views.generic import CreateView, UpdateView


class UserLoginView(LoginView):
    redirect_authenticated_user = True
    template_name = 'clientes/login.html'

    def get_success_url(self) -> str:
        return reverse_lazy('produtos:principal')

    def form_invalid(self, form: AuthenticationForm) -> HttpResponse:
        messages.error(self.request, "USUÁRIO OU SENHA INVÁLIDOS!")
        return super().form_invalid(form)    


class UserCreateView(SuccessMessageMixin, CreateView):
    form_class = UserCreateForm
    template_name = 'clientes/cadastro.html'
    success_url = '/'
    success_message = "Usuário Criado Com Sucesso!"


class UserUpdateView(SuccessMessageMixin, UpdateView):
    model = User
    fields = ['email']
    template_name = 'clientes/atualizar.html'
    success_url = '/'
    success_message = 'Usuário criado!'

    def get_object(self, *args, **kwargs):
        user = super().get_object(*args, **kwargs)
        if not user.pk == self.request.user.pk:
            raise Http404
        return user


def deslogar(request):
    logout(request)
    return redirect(reverse('produtos:principal'))

altamir-master/produtos/views.py
from django.shortcuts import render
from produtos.models import Produto

def index(request):
    produtos = Produto.objects.filter(categoria__nome="Livro")
    return render(request, 'produtos/listar.html', {'produtos': produtos})
    

altamir-master/clientes/templates/clientes/atualizar.html
<div class="container">
    <div class="row">
        <h3>Criar Novo Usuário</h3>
        {% for message in messages %}
            <div class="alert alert-{{message.tags}}" role="alert">
                {{message}}
            </div>
        {% endfor %}
        <form class="row g-3" method="post">
            {% csrf_token %}
            <div class="col-12">
                {{form.as_p}}
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Salvar</button>
            </div>
        </form>
    </div>
</div>

altamir-master/clientes/templates/clientes/cadastro.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
	<title>Login 08</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'clientes/css/style.css'%}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">TELA DE CADASTRO</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-user-o"></span>
						</div>
						<h3 class="text-center mb-4">Preencha os Dados</h3>

						<!-- INICIO FORMULARIO -->
						<form action="#" class="login-form" method="POST">
							{% csrf_token %}
							<div class="form-group">
								<input name="email" type="text" class="form-control rounded-left" placeholder="Informe um Email" required>
							</div>
							<div class="form-group d-flex">
								<input name="password" type="password" class="form-control rounded-left" placeholder="Informe um Senha"
									required>
							</div>
							<div class="form-group d-md-flex">
								<div class="w-50">
									<label class="checkbox-wrap checkbox-primary">
										<a href="{% url 'clientes:login' %}">Retornar ao login</a>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'produtos:principal' %}">Pagina Inicial</a>
								</div>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-primary rounded submit p-3 px-5">
									Criar Conta
								</button>
							</div>
						</form>
					</div>
					<!-- FINAL FORMULARIO -->
				</div>
			</div>
		</div>
	</section>
	<script src="{% static 'clientes/js/jquery.min.js'%}"></script>
	<script src="{% static 'clientes/js/popper.js'%}"></script>
	<script src="{% static 'clientes/js/bootstrap.min.js'%}"></script>
	<script src="{% static 'clientes/js/main.js'%}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

altamir-master/clientes/templates/clientes/login.html
{% load static %}
<!doctype html>
<html lang="pt-br">

<head>
	<title>Login 08</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />

	<link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

	<link rel="stylesheet" href="{% static 'clientes/css/style.css'%}">

</head>

<body>
	<section class="ftco-section">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-md-6 text-center mb-5">
					<h2 class="heading-section">TELA DE LOGIN</h2>
				</div>
			</div>
			<div class="row justify-content-center">
				<div class="col-md-6 col-lg-5">
					<div class="login-wrap p-4 p-md-5">
						<div class="icon d-flex align-items-center justify-content-center">
							<span class="fa fa-user-o"></span>
						</div>
						<h3 class="text-center mb-4">Acessar conta</h3>

						<!-- INICIO FORMULARIO -->
						<form action="#" class="login-form" method="POST">
							{% csrf_token %}
							<div class="form-group">
								<input name="username" type="text" class="form-control rounded-left" placeholder="Email" required>
							</div>
							<div class="form-group d-flex">
								<input name="password" type="password" class="form-control rounded-left" placeholder="Senha"
									required>
							</div>
							<div class="form-group d-md-flex">
								<div class="w-50">
									<label class="checkbox-wrap checkbox-primary">
										<a href="{% url 'clientes:cadastro' %}">Não tem cadastro?</a>
									</label>
								</div>
								<div class="w-50 text-md-right">
									<a href="{% url 'produtos:principal' %}">Pagina Inicial</a>
								</div>
							</div>
							<div class="form-group">
								<button type="submit" class="btn btn-primary rounded submit p-3 px-5">
									ENTRAR
								</button>
							</div>
						</form>
					</div>
					<!-- FINAL FORMULARIO -->
				</div>
			</div>
		</div>
	</section>
	<script src="{% static 'clientes/js/jquery.min.js'%}"></script>
	<script src="{% static 'clientes/js/popper.js'%}"></script>
	<script src="{% static 'clientes/js/bootstrap.min.js'%}"></script>
	<script src="{% static 'clientes/js/main.js'%}"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

altamir-master/produtos/templates/produtos/listar.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Shop Homepage - Start Bootstrap Template</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'produtos/css/styles.css'%}" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" />
</head>

<body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!">Livraria</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#!">Inicial</a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="#!">Sobre</a></li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                            data-bs-toggle="dropdown" aria-expanded="false">Outros</a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#!">Todos os itens</a></li>
                            <li>
                                <hr class="dropdown-divider" />
                            </li>
                            <li><a class="dropdown-item" href="#!">Itens populares</a></li>
                            <li><a class="dropdown-item" href="#!">Novos produtos</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="d-flex">
                    <button class="btn btn-outline-dark" type="submit">
                        <i class="bi-cart-fill me-1"></i>
                        Carrinho
                        <span class="badge bg-dark text-white ms-1 rounded-pill">0</span>
                    </button>
                </form>
                <a href="{% url 'clientes:login' %}" class="btn btn-outline-dark" style="margin-left: 20px;">LOGAR-SE</a> 
            </div>

            {% if user.is_authenticated %}
              <p style="margin: 6px; padding-left: 12px">
                Bem-vindo {{user.email}}
              </p>
              <a href="{% url 'clientes:atualizar_cliente' user.id %}">Meu Perfil</a>
              <a href="{% url 'clientes:deslogar' %}" style="padding-left: 15px">Sair conta</a>
            {% endif %}
        </div>
    </nav>

    <!-- Header-->
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">sua livraria</h1>
                <p class="lead fw-normal text-white-50 mb-0">
                   escolha um dos melhores livros da atualidade 
                </p>
            </div>
        </div>
    </header>

    <!-- Section-->
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center"> 
                <div class="col mb-5">
                    <div class="card h-100">
                        <!-- Sale badge-->
                        <div class="badge bg-dark text-white position-absolute" style="top: 0.5rem; right: 0.5rem">
                            Sale
                        </div>
                        <!-- Product image-->
                        <img class="card-img-top" src="https://dummyimage.com/450x300/dee2e6/6c757d.jpg" alt="..." />
                        <!-- Product details-->
                        <div class="card-body p-4">
                            <div class="text-center">
                                <!-- Product name-->
                                <h5 class="fw-bolder">Special Item</h5>
                                <!-- Product reviews-->
                                <div class="d-flex justify-content-center small text-warning mb-2">
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                    <div class="bi-star-fill"></div>
                                </div>
                                <!-- Product price-->
                                <span class="text-muted text-decoration-line-through">$20.00</span>
                                $18.00
                            </div>
                        </div>
                        <!-- Product actions-->
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                            <div class="text-center">
                                <a class="btn btn-outline-dark mt-auto" href="#">Add to cart</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Footer-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">
                Copyright &copy; Your Website 2023
            </p>
        </div>
    </footer>
    <!-- Core theme JS-->
    <script src="https://unpkg.com/blip-chat-widget" type="text/javascript"></script>
    <script>
        (function () {
            window.onload = function () {
                new BlipChat()
                    .withAppKey('YWx0YW1pcmQ6MzQ0OTUwNGMtNmQwMS00Y2U1LTlkYWItYmNkNjY0YzBkNGEx')
                    .withButton({"color":"#0096fa","icon":""})
                    .withCustomCommonUrl('https://altamir-da-cb-cgzgo.chat.blip.ai/')
                    .build();
            }
        })();
    </script>
                
</body>

</html>